create table nick (id int8 generated by default as identity, city varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), phone varchar(255), state varchar(255), primary key (id));
create table pets (id int8 generated by default as identity, adopted boolean not null, breed varchar(255), image varchar(255), name varchar(120) not null, species varchar(120), weight float8, adopter_id int8, user_id int8, primary key (id));
alter table if exists pets add constraint FKsic845baqqa9u9t1e4w4hgq4l foreign key (adopter_id) references nick;
alter table if exists pets add constraint FKghejc7km4xv5ivq15xcqcyfvn foreign key (user_id) references nick;
create table nick (id int8 generated by default as identity, city varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), phone varchar(255), state varchar(255), primary key (id));
create table pets (id int8 generated by default as identity, adopted boolean not null, breed varchar(255), image varchar(255), name varchar(120) not null, species varchar(120), weight float8, adopter_id int8, user_id int8, primary key (id));
alter table if exists pets add constraint FKsic845baqqa9u9t1e4w4hgq4l foreign key (adopter_id) references nick;
alter table if exists pets add constraint FKghejc7km4xv5ivq15xcqcyfvn foreign key (user_id) references nick;
