create table pets (id int8 generated by default as identity, adotado boolean not null, imagem varchar(255), nome varchar(120) not null, peso float8, raca varchar(255), tipo varchar(120), adotante_id int8, usuario_id int8, primary key (id));
create table usuario (id int8 generated by default as identity, cidade varchar(255), contato varchar(255), email varchar(50), estado varchar(50), nome varchar(120) not null, primary key (id));
alter table if exists pets add constraint FKgysy4oayd1qfpg8ip2cwfovge foreign key (adotante_id) references usuario;
alter table if exists pets add constraint FK6qg05r6gf7a9skp0rky079hra foreign key (usuario_id) references usuario;
